<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'foo' => '/test/test.php',
                'theseer\\autoload\\application' => '/Application.php',
                'theseer\\autoload\\applicationexception' => '/Application.php',
                'theseer\\autoload\\autoloadbuilderexception' => '/AutoloadRenderer.php',
                'theseer\\autoload\\autoloadrenderer' => '/AutoloadRenderer.php',
                'theseer\\autoload\\classdependencysorter' => '/DependencySorter.php',
                'theseer\\autoload\\classdependencysorterexception' => '/DependencySorter.php',
                'theseer\\autoload\\classfinder' => '/ClassFinder.php',
                'theseer\\autoload\\classfinderexception' => '/ClassFinder.php',
                'theseer\\autoload\\cli' => '/CLI.php',
                'theseer\\autoload\\config' => '/Config.php',
                'theseer\\autoload\\factory' => '/Factory.php',
                'theseer\\autoload\\logger' => '/Logger.php',
                'theseer\\autoload\\pharbuilder' => '/PharBuilder.php',
                'theseer\\autoload\\staticrenderer' => '/StaticRenderer.php',
                'theseer\\autoload\\version' => '/Version.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd