<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\autoload\\autoloadbuilder' => '/autoloadbuilder.php',
                'theseer\\autoload\\autoloadbuilderexception' => '/autoloadbuilder.php',
                'theseer\\autoload\\classdependencysorter' => '/dependencysorter.php',
                'theseer\\autoload\\classdependencysorterexception' => '/dependencysorter.php',
                'theseer\\autoload\\classfinder' => '/classfinder.php',
                'theseer\\autoload\\classfinderexception' => '/classfinder.php',
                'theseer\\autoload\\cli' => '/cli.php',
                'theseer\\autoload\\staticbuilder' => '/staticbuilder.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd